# ----------------------------------------------------------------------------------
# hypridle configuration: Locks screen and turns off display on inactivity
# ----------------------------------------------------------------------------------

# GENERAL SECTION
general {
    # This prevents multiple instances of hyprlock from running if you 
    # accidentally try to lock the screen twice.
    lock_cmd = pidof hyprlock || hyprlock 

    # Command to run before the system goes to sleep/suspend
    # loginctl lock-session is the standard way to trigger the lock immediately before suspend
    before_sleep_cmd = loginctl lock-session 

    after_sleep_cmd = loginctl lock-session   # re-lock after hibernate resume
}

# LISTENER 1: LOCK SCREEN
listener {
    # Timeout in seconds (5 minutes)
    timeout = 300 

    # Command to run when the timeout is reached
    on-timeout = loginctl lock-session 
}

# LISTENER 2: TURN OFF SCREEN (DPMS)
listener {
    # Timeout 30 seconds after the lock screen appears (5.5 minutes total)
    timeout = 330 

    # Command to turn the display off (Display Power Management Signaling)
    on-timeout = hyprctl dispatch dpms off 

    # Command to run when activity resumes (turn the display back on)
    on-resume = hyprctl dispatch dpms on 
}

# LISTENER 3: Hibernate
listener {
   timeout = 1800 # 30 minutes
   on-timeout = systemctl hibernate
}
