include current-theme.conf
# --- Font Settings ---
font_family        JetBrainsMono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          13.0


# Set the opacity level. 1.0 is fully opaque, 0.1 is very transparent.
background_opacity 0.8

map alt+e launch --type=overlay --cwd=current sh -c 'file=$(fzf) && [ -n "$file" ] && nvim "$file"'
map alt+m send_text all activate_env\r

# Enable the "Tall" layout (Master window on left, others on right)
enabled_layouts tall, stack

# Keybindings to create and navigate windows
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
# Resize windows with arrows
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider

# Keybindings to create and navigate tabs
map ctrl+shift+t new_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab


map ctrl+shift+t new_tab_with_cwd

allow_remote_control yes
